### PR TITLE
Feature/improved database loading

### LINKED ISSUE #164: MemoryError while generating cache file of Full HITEMP CH4 database
### 🐛 Describe the bug

Reaching hardware limits ! 

While trying to process all of the new HITEMP 2020 CH4 lines, I systematically get Memory Error during generation of the .h5 cache file, despite 16 Gb RAM on my computer. 
`06_HITEMP2020.par` is 5 Gb, .h5 are usually a bit bigger so we end up with > 10 Gb in RAM. 

### 🖥 Steps To Reproduce

Code 

``` 

from radis import calc_spectrum
from astropy import units as u

test_conditions = {
    'wavenum_min':1000 / u.cm,
    'wavenum_max':10000 / u.cm,
    'Tgas':3000 * u.K,
    'pressure':1 * u.bar,
    'molecule':'CH4',
    'isotope':'1',
    'cutoff':0,
    'databank':"./06_HITEMP2020.par",
    'verbose':3,
}

calc_spectrum(**test_conditions).plot()

```

### 💡 Possible solutions

Time for a better loading and processing of the .par files. 
- we do not need all of the columns there! 
- should be added to the cache only the required information. 
- btw, maybe we should directly work from the .par.bz2 compressed files.

### LINKED ISSUE #180: Clear some warnings in base examples
### 🎯 Todo

Running the start example creates a warning
```
from radis import calc_spectrum
s = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  )
s.apply_slit(0.5, 'nm')       # simulate an experimental slit
s.plot('radiance')
```

```
...radis\radis\misc\warning.py:241: MissingSelfBroadeningWarning: Self-broadening temperature coefficient Tdpsel not given in database: used Tdpair instead
  warnings.warn(WarningType(message))
```

Which is there for a reason : there is no temperature-dependance coefficient available for resonant broadening for most molecules in the HITRAN (and others) database.

This involves the physics therefore it was chosen to trigger a warning. 

However : 

- this warning in the welcome script can be disturbing to users, as reported by @gugzy 
- RADIS users can't anyway do anything about it : it's a limitation of the line databases (and it's very unlikely most databases will provide such coefficients anytime soon).

Therefore the warning could be discarded. I see one easy solution : 

- introduce different levels of warnings, correlated with the `verbose` level of the calculation, i.e., this warning could be considered a warning of level=1 or 2, i.e., only appears when verbose=True or verbose>=2, respectively. 
- most physics-related warnings remain of level "verbose=0", i.e., are still triggered with `verbose=False`

### LINKED ISSUE #182: fetch_databank doesnt read use_cached='regen'
### 🐛 Describe the bug

Instead it reads it as use_cached=True

### 💡 Diagnostic

This is because [fetch_databank()](https://github.com/radis/radis/blob/7afa817a7b79d9cc036552c0503677152df514b0/radis/lbl/loader.py#L936) calls fetch_astroquery without forwarding the use_cached argument.

- [x] fix : forward the argument 
- [ ] add a test ! 

Note : this [existing_test](https://github.com/radis/radis/blob/8fb445539125517b91209eb728fa7021383949e0/radis/test/io/test_query.py#L44) of fetch_astroquery does not seem to check the `cached='regen'` option, making sure that the database cache was regenerated. A full test should be added in  [test_loader](https://github.com/radis/radis/blob/develop/radis/test/lbl/test_loader.py).   A working test  with `cached='regen'` can be found in [test_partfunc](https://github.com/radis/radis/blob/4c33c453d26dc25597a1d072b31e16a920e99acb/radis/test/levels/test_partfunc.py#L67) which checks that rovibrational energies cache is recomputed. It could be adapted !

### LINKED ISSUE #188: Read HDF5 files directly
### 🎯 Describe what you'd like

Read HDF5 files directly. 
(currently they can only be read if they are the cache-files of something else)

HDF5 was identified to be the best format for high performance in RADIS. 
See discussion on 💬 [Slack](https://radis-radiation.slack.com/archives/C018C2MH5AB/p1610840168006600)

Related:  #34 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

### PR DESCRIPTION
**Pull request by erwanp**
### Description

Major improvements on database handling : 

- [x] Read HDF5 files directly. Fixes #188 
- Automatically fetch from HITEMP (similar to how we automatically fetch HITRAN already)
   - [x] Generates HDF5 files in RADIS-readable format, in new ~/.radisdb folder 
   - [x] Unzip and generate the file chunk-by-chunk, which prevents MemoryErrors. Fixes #164  
   - [x] add databases to ~/.radis config file  
   - [x] (wip) still missing the last chunk of lines
   - [ ] *[wont do here]* Automatically grow HDF5 files to allow building only smaller ranges : (unzip a part of the file only ? )
   - [x] reindex df properly 
   - [x] add metadata (link, time-downloaded, min/max, etc.)
   - [x] do not re-download if HDF5 exists  (currently DataSource is initialized)
   - [ ] *[wont do here]*  clean DataSource downloads after HDF5 is generated ? (only if HDF5 is fully_unzipped)
- [ ] *[wont do here]* only load required columns from the H5 files. Related to #118  . 
  - [ ] *[wont do here]* Have metadata in fetch_hitemp
- [x] update SpectrumFactory.fetch_databank() to use 'hitran' and 'hitemp' arguments. Keep 'fetch' as 'hitran' with DeprecatedWarning
- [x] add test
- [x] fix tests on Travis-CI  (try on Linux locally ?)

Other Improvements: 
- [x] add cache='regen' option on fetch_hitran (through astroquery). Fixes #182 
- [x] generalized the implementation of metadata to discard irrelevant files based on the work of @CorentinGrimaldi  #131 #185  
- [x] introduce a verbose-level dependant warning, to trigger the 'absence of resonant temperature dpeendance coefficient' warning only for verbose>=2. Fixes #180 

---

TODO post first feedbacks: 

- [x] make it work for NO, NO2, etc (all molecules)
- [x] add tests for all these molecules (but deactivated by default to prevent large database download and save some 🌳 )
- [x] deal with ``'HITEMP-OH not declared in your RADIS ~/.config file although C:\.../OH-13_HITEMP2020.h5 exists. '``. Update ~/.radis if metadata looks good. 
- [x] Add metadata flag when Database is fully complete. ("complete"?). Safety: check min/max when loading the database, and compare with the metadata ?  _[no flag but we added]_
- [x] Add info on total number of lines for each database. Give an insight on the number of lines remaining during download & expected time. 
- [ ] add user warning & confirmation if dwnloading huge databases (> 50 MB)

---

### Try 

```python

from astropy import units as u
from radis import calc_spectrum
calc_spectrum(
    wavenum_min=2500 / u.cm,
    wavenum_max=4500 / u.cm,
    molecule="OH",
    Tgas=3000,
    databank="hitemp",  # fetch directly
)



```

### CODE REVIEW

**Comment by ulyssed** [comment]
```
from astropy import units as u
from radis import calc_spectrum
calc_spectrum(
    wavenum_min=2500 / u.cm,
    wavenum_max=4500 / u.cm,
    molecule="OH",
    Tgas=3000,
    databank="hitemp",  # fetch directly
)
There was a problem looking for database name: hitemp
/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/publib/main.py:139: MatplotlibDeprecationWarning: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  mpl.style.use(stl)
/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/_collections_abc.py:841: MatplotlibDeprecationWarning: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  self[key] = other[key]
Traceback (most recent call last):

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]

KeyError: 'hitemp'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/radis/misc/config.py", line 238, in getDatabankEntries
    config.get(dbname, "path")

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)

NoSectionError: No section: 'hitemp'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-8607aea36b69>", line 8, in <module>
    databank="hitemp",  # fetch directly

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/radis/lbl/calc.py", line 451, in calc_spectrum
    **kwargs_molecule

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/radis/lbl/calc.py", line 636, in _calc_spectrum
    drop_columns=drop_columns,

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/radis/lbl/loader.py", line 1192, in load_databank
    buffer=buffer,

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/radis/lbl/loader.py", line 1305, in _check_database_params
    entries = getDatabankEntries(name)

  File "/home/dubuetu/anaconda3/envs/Py36/lib/python3.6/site-packages/radis/misc/config.py", line 248, in getDatabankEntries
    raise DatabankNotFound(msg)

DatabankNotFound: hitemp
DBFORMAT

--------------------------

[MY-HITEMP-CO2]                  #  your databank name: use this in calc_spectrum()
                                 #  or SpectrumFactory.load_databank()
info = HITEMP 2010 databank      #  whatever you want
path =                           #  no "", multipath allowed
       D:\Databases\HITEMP-CO2\hitemp_07
       D:\Databases\HITEMP-CO2\hitemp_08
       D:\Databases\HITEMP-CO2\hitemp_09
format = hitran                  #  'hitran' (HITRAN/HITEMP), 'cdsd-hitemp', 'cdsd-4000'
                                 # databank text file format. More info in
                                 # SpectrumFactory.load_databank function.
parfuncfmt:                      #  'cdsd', 'hapi', etc.
                                 # format to read tabulated partition function
                                 # file. If `hapi`, then HAPI (HITRAN Python
                                 # interface) is used to retrieve them (valid if
                                 # your databank is HITRAN data). HAPI is embedded
                                 # into RADIS. Check the version.
# Optional
# ----------
parfunc:                         #  path to tabulated partition function to use.
                                 # If `parfuncfmt` is `hapi` then `parfunc`
                                 # should be the link to the hapi.py file. If
                                 # not given, then the hapi.py embedded in RADIS
                                 # is used (check version)
levels_iso1                      #  path to energy levels (needed for non-eq
                                 # calculations). Default None
levels_iso2                      # etc
levels_iso4                      # etc
levelsfmt:                       #  'cdsd', etc.
                                 # how to read the previous file. Default None.
levelsZPE:                       #  zero-point-energy (cm-1): offset for all level
                                 # energies. Default 0 (if not given)

--------------------------
No databank named hitemp in `/home/dubuetu/.radis`. Available databanks: ['HITRAN-CO2-TEST', 'HITRAN-CO-TEST', 'HITEMP-CO2-TEST', 'HITEMP-CO-DUNHAM', 'CDSD-4000', 'CDSD-4000-SMALL', 'HITEMP-2016-CO2', 'HITEMP-2019-CO', 'HITEMP-2010-H2O', 'HITEMP-2019-NO', 'HITEMP-2020-OH']. See databank format above. More information in https://radis.readthedocs.io/en/latest/lbl/lbl.html#configuration-file
```

**Comment by erwanp** [comment]
@dcmvdbekerom @CorentinGrimaldi @ulyssed  : this is ready : automatic HITEMP calculations as simple as HITRAN !

Many files changed so I don't expect you to review everything. Just try the example and try to play around !

**Comment by dcmvdbekerom** [comment]
Well done guys, very cool to have this feature!

I did get an error when running the OH-demo:

```
Traceback (most recent call last):
  File "C:\Users\dcmvd\Documents\GitHub\radis\build\test_hitemp.py", line 8, in <module>
    databank="hitemp",  # fetch directly
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\calc.py", line 442, in calc_spectrum
    **kwargs_molecule
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\calc.py", line 575, in _calc_spectrum
    sf.fetch_databank(**conditions)
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\loader.py", line 982, in fetch_databank
    verbose=self.verbose,
  File "c:\users\dcmvd\documents\github\radis\radis\io\hitemp.py", line 275, in fetch_hitemp
    verbose=verbose,
  File "c:\users\dcmvd\documents\github\radis\radis\io\hdf5.py", line 92, in hdf2df
    df.attrs.update(store.get_storer("df").attrs.metadata)
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py", line 5179, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'attrs'
```

But upgrading my pandas installation solved the trick!
(I was too late to check what my old Pandas version was...)

**Comment by dcmvdbekerom** [comment]
A question and an issue...:
Question; when I try to plot methane in the range 2500 cm-1 and 4500 cm-1, it downloads the database from 0cm-1 to 13398.7 cm-1 (presumably the entire database). Is that the intended behavior?

Then, after downloading I get the following error message:

```
Traceback (most recent call last):
  File "C:\Users\dcmvd\Documents\GitHub\radis\build\test_hitemp.py", line 8, in <module>
    databank="hitemp",  # fetch directly
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\calc.py", line 442, in calc_spectrum
    **kwargs_molecule
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\calc.py", line 575, in _calc_spectrum
    sf.fetch_databank(**conditions)
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\loader.py", line 1005, in fetch_databank
    self._fetch_molecular_parameters(df)
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\loader.py", line 2441, in _fetch_molecular_parameters
    raise ValueError("No molecule defined in this database.")
ValueError: No molecule defined in this database.
```

**Comment by erwanp** [comment]
Thank for you testing! 

Regarding the first : could you update the environment.yml to have Pandas>= a working version? Maybe not the latest but for instance the latest Anaconda supported one

**Comment by erwanp** [comment]
Regarding 2 :

- full download is mandatory. HITEMP stores the files as compressed bz2,  these have no index and you cannot know how much in advance.
- it may be possible to read and store on disk only what you want.  This saves space.  However you should make sure to know which range you've discarded.  It'd error prone and I chose to implement a safer one instead : load everything and let the Hdf5 handle the partial loading at runtime. 

If you think it was long we could add some additional prints and an expected time.

**Comment by erwanp** [comment]
3 : that's a true error. Can you create an Issue in this repo from the comment? (Github lets you do)  We'll fix it there. 

Well done for finding it! 

(on my own test it worked. I didn't implement it online because I don't want to burn the planet computing a full CH4 linelist for each test!)

**Comment by dcmvdbekerom** [comment]
Hey, I don't think I can open an issue on your fork..
By the way, the issue is with every molecule other than OH, not just CH4

**Comment by erwanp** [comment]
Thanks @dcmvdbekerom for finding this out. The function I used to build the local HDF5 database was overwriting the 'append' behavior with 'write', therefore any database large enough to be built on several iterations (this included everything but OH) only contained the last lines. Fixed with many other improvements in b2f8889

Also, you should be able to push to my repo, at least the erwanp:feature/improved-database-loading, because by opening the PR I grant write access to RADIS Maintainers and you're one of them. Can you check again ? Maybe something is wrong.

**Pull request merged**
