### PR TITLE
Gpu widget bug fix

### PR DESCRIPTION
**Pull request by dcmvdbekerom**
Fixes https://github.com/radis/radis/issues/418

### CODE REVIEW

**Comment by erwanp** [comment]
Test failure is unrelated 

https://app.travis-ci.com/github/radis/radis/jobs/554024187

>     #cython: language_level=3
> E   ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject

Seems to be related to a Numpy version https://stackoverflow.com/questions/60323366/valueerror-numpy-ufunc-size-changed-may-indicate-binary-incompatibility-expec



We could ensure that Numpy version is always compatible, but this sounds like a lot of maintenance work eventually.  We could also decide to escape this error and switch back to numpy add_at . Would be done by adding `except (ValueError, ModuleNotFoundError)`  in [arrays.py L477](https://github.com/radis/radis/blob/develop/radis/misc/arrays.py#L477)

**Comment by dcmvdbekerom** [comment]
I escaped it for now, didn't we have a flag that reports which add_at is used? It would have to be set in the code block you highlighted. I'm worried that this will result in always using numpy's add at. Did we ever try jit compilation?

**Comment by erwanp** [comment]
It's in the Spectrum properties. "add_at_used". 

We could add a "check_performance" function that ensures that everything is properly activated, and return tips on how to improve performances.

**Review by erwanp — APPROVED** [review]
can merge!

**Pull request merged**
