### PR TITLE
Modified codebase to use df.attrs instead of df._metadata

### LINKED ISSUE #300: Use only one of `df_metadata` or `df.attrs`
### 🎯 Todo

Post #287 #302 and a few other changes to the dataframe that will follow, a lot of columns in the dataframe will be made as attributes of the dataframe instead of an entire column. We are currently using `df_metadata`  (a manually created dictionary) and `df.attrs` (an inbuilt dataframe attribute) to handle this. Remove one of these in the codebase. 

### 💡 Possible implementations

It would be easier to remove `df_metadata` since we are using `df.attrs` at a lot of places. `df_metadata` is just used at a few places (most probably just two) while transferring the metadata using [transfer_metadata](https://github.com/radis/radis/blob/7b3a447b88a4cabd6fcb66fbbbc487a82d7a6676/radis/misc/basics.py#L345)  just replace it with a `df.attrs`.

Good Issue for anyone who wants to get started with Radis since the implementation is simple. 

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

### PR DESCRIPTION
**Pull request by MVAMULYA**
### Description

This pull request is to replace df._metadata with df.attrs for storing data frame attributes. 

Fixes #300

### CODE REVIEW

**Review by erwanp — APPROVED** [review]
Well done ! Can you confirm there is no `._metadata` anywhere in the code? 

If so, you can convert the PR as "Ready for Review". If the automatic tests don't start, you may need to push another commit to trigger them. One possible thing is to look for [broken links in the docs](https://radis.readthedocs.io/en/latest/) and fix one.

**Comment by MVAMULYA** [comment]
> Well done ! Can you confirm there is no `._metadata` anywhere in the code?
> 
> If so, you can convert the PR as "Ready for Review". If the automatic tests don't start, you may need to push another commit to trigger them. One possible thing is to look for [broken links in the docs](https://radis.readthedocs.io/en/latest/) and fix one.

yes. There are no reference to '._metadata' anywhere in the code.

**Comment by MVAMULYA** [comment]
I have made changes to all references to '._metadata' in the code. The changed code passed all the checks and found no conflicts with base branch.

**Review by erwanp — APPROVED** [review]
All good, merging ! Welcome to the RADIS contributors ;)

**Pull request merged**
