### PR TITLE
fixes invalidindex error

### LINKED ISSUE #427: pandas InvalidIndexError error in df.at
### 🐛 Describe the bug

For Pandas >=1.4, some change in df.at()  fails our calls to df.at[idx, "Qvib"]  with InvalidIndexError

```
File ~/radis/radis/test/lbl/test_calc.py:101 in test_calc_spectrum
    s = calc_spectrum(

  File ~/radis/radis/lbl/calc.py:508 in calc_spectrum
    generated_spectrum = _calc_spectrum_one_molecule(

  File ~/radis/radis/lbl/calc.py:827 in _calc_spectrum_one_molecule
    s = sf.non_eq_spectrum(

  File ~/radis/radis/lbl/factory.py:1570 in non_eq_spectrum
    self.calc_populations_noneq(

  File ~/radis/radis/lbl/base.py:2675 in calc_populations_noneq
    Q, Qvib, Qrotu, Qrotl = self.Qneq_Qvib_Qrotu_Qrotl(

  File ~/radis/radis/lbl/base.py:2455 in Qneq_Qvib_Qrotu_Qrotl
    df.at[idx, "Qvib"] = Qvib

  File ~/anaconda3/envs/radis-env/lib/python3.8/site-packages/pandas/core/indexing.py:2274 in __setitem__
    return super().__setitem__(key, value)

  File ~/anaconda3/envs/radis-env/lib/python3.8/site-packages/pandas/core/indexing.py:2229 in __setitem__
    self.obj._set_value(*key, value=value, takeable=self._takeable)

  File ~/anaconda3/envs/radis-env/lib/python3.8/site-packages/pandas/core/frame.py:3869 in _set_value
    loc = self.index.get_loc(index)

  File ~/anaconda3/envs/radis-env/lib/python3.8/site-packages/pandas/core/indexes/range.py:388 in get_loc
    self._check_indexing_error(key)

  File ~/anaconda3/envs/radis-env/lib/python3.8/site-packages/pandas/core/indexes/base.py:5637 in _check_indexing_error
    raise InvalidIndexError(key)

InvalidIndexError: [  7  11  15  22  24  35  41  49  51  65  66  70  76  91  99 105 125 129
 132 138 155 158 166 186 188 197 205 213 218 225 230 233 242 250 262 264
 273 282 289 290 293 295 311 312 313 318 321 324 325 332 334 335 337 338
 343 344 346 348 355 358 360 366 367 368 374 375 378 381 384 386 387 388
 389 390 392 394 395 396 406 410 411 423 426 427 428 437 441 442 448 449
 453 455 461 467 468 471 475 478 486 487 488 493 502 508 515 516 521 524
 525 528 532 534 538 542 544 546 550 551 553 558 561 564 565 568 570 572
 574 577 584 585 588 591 592 593 595 596 604 606 609 614 623 639 640 646
 649 658 659]
```

Seen in the test suites of #420, #422, #425, #426

### 🖥 Steps To Reproduce

Run radis/test/lbl/test_calc.py for instance

### 💡 Possible solutions

Using df.loc() instead of df.at() seems to work, with maybe some impacts on performances ( Stackoverflow : .At() is an optimized version of .loc() when returning a unique value https://stackoverflow.com/questions/37216485/pandas-at-versus-loc )

### PR DESCRIPTION
**Pull request by erwanp**
### Description

replace .at() by .loc() . Fixes #427

### CODE REVIEW

**Comment by anandxkumar** [comment]
tested the same on my system, `test_array` 2 tests fails. One is caused by `AssertionError: assert 'numpy' == 'cython'
` and other on my system says `ModuleNotFoundError: No module named 'radis_cython_extensions'` where as on Travis says value error which happens when  `radis_cython_extensions` successfully gets imported. Due to same `radis_cython_extensions` the 2 tests in `test_examples` fails.

**Comment by erwanp** [comment]
Cython build failed recently, causing the errors above. 

I found out it was because we specify Cython & numpy requirements both in [https://github.com/radis/radis/blob/develop/pyproject.toml](pyproject.toml) (the new python standard) as well as in the setup.py (setuptools standard)  

Things will be smoother once Setuptools totally supports pyproject.toml (which is being worked on : https://github.com/pypa/setuptools/pull/2970  )

**Comment by anandxkumar** [comment]
@erwanp the code quality check failed. I haven't seen error similar to the below:
`The command "eval git fetch origin +refs/pull/428/merge: " failed 3 times.`

**Comment by erwanp** [comment]
Fixed and merged in #426  👍

**Pull request merged**
