### PR TITLE
0.9.26

### PR DESCRIPTION
**Pull request by erwanp**
# 0.9.26

Featuring new major functionalities such as GPU support for equilibrium calculations (see [GSoC 2020 project](https://github.com/radis/radis/projects/2), congrats @pkj-m ), many bug fixes and perf improvement (new DLM model by @dcmvdbekerom , paper soon !), and some neat new interface features (multi-molecules @ulyssed  )

Main changes since [0.9.25](https://github.com/radis/radis/pull/70) (Feb 7) : 

## (Physical) Features 

- adding initial effective Hamiltonian support directly into Radis : #91 

## User-interface 

- read all datafiles in a folder directly : #107 
- dimensioned wmin, wmax parameters directly in calc_spectrum / SpectrumFactory : #96 
- added dimensioned units support : #106 
- calculate multiple molecules directly #108
- new .min(), .max(), .normalize() methods #122 
- new .take() method to return a Spectrum with a single a spectral quantity , useful for chaining, ex : `Spectrum.take('radiance').max()`   #133 

## Performance improvement

- GPU calculations following the Google Summer of Code Project ! Congrats @pkj-m 🎉  #117 
- improve .spec loading/writing times #86  
- improve DLM accuracy : #115 implemented by #116  #130 

## Bug fixes

- #82 fixed by #83 
- #85 fixed by #88
- #109 fixed by #122 
- #87 
- #102 fixed by #120 
- #121 fixed by #123 

## Reliability  / Tests

- more automatic tests : #99 
- #90 : "Regenerate levels file automatically if manually changed " safety feature to prevent potential bug 
- #100  
- Test coverage improved from 70% to ~77% but still not the 80% required for #62 

## Documentation 

- new contribution guides : #71, #75 
- fix link #132 
- [new Slack invite](https://radis.github.io/slack-invite/)

---

Not fixed yet in 0.9.26 : 

- #78 and #80 **(NOT DONE YET)**

### CODE REVIEW

**Comment by erwanp** [comment]
@minouHub @dcmvdbekerom we're finally ready. Mostly asking for your review on the list of changes, no need to go through the code : everything has been validated already !!

**Comment by dcmvdbekerom** [comment]
Looks good to me! Though I thought you wanted to add GPU support in the 1.0 version?

**Comment by erwanp** [comment]
We'll have full GPU support in the 1.0, right now it's limited to equilibrium calculations only, and will serve as a beta !

**Comment by minouHub** [comment]
Sorry guys, did not have time to review it. Quick message to say well done!

**Pull request merged**
