### PR TITLE
Fixed inaccessible links in several documents

### PR DESCRIPTION
**Pull request by TranHuuNhatHuy**
### Description
This pull request is to correct the inaccessible links in several documentations, mentioned in [#439](https://github.com/radis/radis/issues/439).

### CODE REVIEW

**Comment by anandxkumar** [comment]
Hi @TranHuuNhatHuy, you may want to pull the latest development branch in your repo and then run `pre-commit run --all-files` before pushing code back or better use `git commit -am "message"` to run linting before committing the changes , if the test fails run the  `git commit -am "message"` again to save the changes

**Comment by anandxkumar** [comment]
The test failed but for test and coverage, not related to your code. You may want to trigger Travis again by committing an empty commit i.e. `git commit --allow-empty -m "Trigger"`

**Comment by TranHuuNhatHuy** [comment]
Hello @anandxkumar. Thank you so much for helping me. I tried to commit an empty commit in order to trigger Travis again but somehow it doesn't respond. Should I wait for a while before retrying?

**Comment by anandxkumar** [comment]
Are you sure that you pshed the commit, because it is not showing here in the PR. Try `git commit --allow-empty -m "Trigger"`.

**Comment by anandxkumar** [comment]
Tests passed, nice work!

**Comment by TranHuuNhatHuy** [comment]
@anandxkumar Thanks to your wholesome support !

**Pull request merged**
