### PR TITLE
Handles division by zero

### LINKED ISSUE #565: Bug Report: divide-by-zero warning in conversion from nm to cm-1
### 🐛 Describe the bug

I haven't used Radis in a while; I just merged the development branch into my local branch, and now get the following warning when running a number of examples:

Warning (from warnings module):
  File "c:\users\dcmvd\documents\github\radis\radis\phys\convert.py", line 126
    return 1 / wl_nm * 1e9 / 100
RuntimeWarning: divide by zero encountered in true_divide

It looks like the problem is that the wl_nm axis includes a zero value; however, this should not normally be the case.

### 💡 Possible solutions

Figure out where/when/why the spectral axis becomes zero

### 🎲 Radis version

0.14

### 💻 Operating system

Windows

### PR DESCRIPTION
**Pull request by 1someshverma**
This is to fix #565 

To solve this issue I have added to methods div_safe and zero2inf to convert.py

zero2inf converts zeroes to infinity thus avoiding division by zero.
div_safe uses zero2inf to convert zeroes.

I have passed it to the parameter in secondary axis functions to avoid division by zero error.

### CODE REVIEW

**Comment by erwanp** [comment]
@dcmvdbekerom can you review ? I think it's good. Test failing is not related (linting #564 )

**Comment by 1someshverma** [comment]
@minouHub I have merged the radis:develop into this but as the HITRAN server is down many test cases are not passing.

**Comment by minouHub** [comment]
This example code:

```python
from radis.test.utils import getTestFile
from radis.tools.database import load_spec

my_file = getTestFile("CO2_measured_spectrum_4-5um.spec")  # for the example here

s = load_spec(my_file)
s.plot()
```

provides this output (+ the graph):
```python
C:\Anaconda\lib\site-packages\matplotlib\transforms.py:365: RuntimeWarning: invalid value encountered in scalar subtract
  return points[1, 0] - points[0, 0]
```

Could you please check what is happening?

**Comment by 1someshverma** [comment]
Ok i will check and resolve this.

**Comment by erwanp** [comment]
(that's an experimental spectrum recorded few years ago; so very unexpected values could be in there)

**Comment by minouHub** [comment]
Same output using a calculated spectrum
```python
from radis import calc_spectrum
s = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=300,
                  mole_fraction=0.1,
                  databank='hitran',  # or 'hitemp'
                  diluent = "air",     # or {'CO2': 0.1, 'air':0.8}
                  verbose=0
                  )
s.plot()
```
gives:
```
C:\Anaconda\lib\site-packages\matplotlib\transforms.py:365: RuntimeWarning: invalid value encountered in scalar subtract
  return points[1, 0] - points[0, 0]
```

**Comment by erwanp** [comment]
@1someshverma do you have ideas on how to fix the latest warning ?

**Comment by 1someshverma** [comment]
I am not able to reproduce the latest warning. I ran this code on branch origin/1someshverma/radis2, and I haven't got any warning 
Screenshot at 2023-08-01 21-41-21

```
from radis import calc_spectrum
s = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=300,
                  mole_fraction=0.1,
                  databank='hitran',  # or 'hitemp'
                  diluent = "air",     # or {'CO2': 0.1, 'air':0.8}
                  verbose=0
                  )
s.plot()
```

**Comment by minouHub** [comment]
Alright, it's on my side then. Merging! 🎉

**Pull request merged**
