### PR TITLE
New Spectrum.fit_model() routine, s.argmax(), and s.from_mat() for Matlab interface 

### PR DESCRIPTION
**Pull request by erwanp**
### Description

New useful interface functions : 
- [x]  ```s.argmax(), s.argmin()``` => returns wavenumber (or wavelength) of maximum, minimum of Spectrum
- [x] ```s.fit_model(model)``` ==> fit a lineshape on a Spectrum (based on astropy models for Voigt, Lorentzian, Gaussian, and more, and an arbitrary combination of those ) 
- [x] ```Spectrum.from_mat(file)``` to load a Matlab file directly
- [x] Improved docs, fix (many!) typos
- [x] also added a quick hack to make Radis Matlab-syntax code appear in the online documentation. (@1someshverma have a look at the file [plot_calc_matlab.m.py](https://github.com/radis/radis/pull/611/files#diff-79675ef26de9fb5953efb0a097a11e1b7438c0770fb89e0d6f3c56f26c7cb6a6) for Review)
- [x] prepare 0.15 version number 

### Example

All of these are combined in the following new example : fit 3 Voigt profiles based on a Matlab experimental file by @minouHub 

```python

from radis import Spectrum
from radis.test.utils import getTestFile

s = Spectrum.from_mat(
    getTestFile("trimmed_1857_VoigtCO_Minesi.mat"),
    "absorbance",
    wunit="cm-1",
    unit="",
    index=10,
)


# %%
# Fix baseline & Fit 3 Voigts profiles :
from astropy.modeling import models

s += 0.002
s.fit_model(
    [models.Voigt1D() for _ in range(3)], confidence=0.9545, plot=True, verbose=True
)
```

image

### Future work
- [ ] Returned confidence intervals in ```s.fit_model(model)``` are still to be confirmed

### CODE REVIEW

**Review by 1someshverma — APPROVED** [review]

**Review by minouHub — APPROVED** [review]
Sent multiple commits to include compatibility with inline plotting. I also show in the example with the CO spectrum at 7000 K that the fitting is working fine. @erwanp merge if you are happy with these changes.

**Comment by minouHub** [comment]
@erwanp I don't think the last bullet "Returned confidence intervals in s.fit_model(model) are still to be confirmed" is needed. For me, RADIS rely and trust astropy, that's it.

**Review by erwanp — COMMENTED** [review]
ok good for me; merging !


Edit : rebased; fixed conflict

**Comment by erwanp** [comment]
(linting failed, merging anyway)

**Pull request merged**
