### PR TITLE
Deploy to anaconda 

### LINKED ISSUE #278: Deploy Radis on Anaconda
### 🎯 Todo

Will be much easier to deal with all dependencies and C-compiled components. 

Issue open to be taken, if anyone is experienced with publishing Conda packages !

### 💡 Possible implementations

- https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf
- [How to Setup Automatic Uploads to Anaconda from Travis CI in 15 minutes ?](https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9)
- [Building a Conda recipee](https://conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#building-a-conda-recipe)

---

### PR DESCRIPTION
**Pull request by arunavabasu-03**
Fixes #278 
This pull request contains the ci setup to deploy radis to anaconda .Hey @erwanp  @anandxkumar , please check .

### CODE REVIEW

**Comment by erwanp** [comment]
Excellent! How can we test it?

**Review by erwanp — APPROVED** [review]

**Comment by erwanp** [comment]
@arunavabasu-03 how can this be tested before merging ?

**Comment by arunavabasu-03** [comment]
ok @erwanp, I look at the testing part.

**Comment by anandxkumar** [comment]
Hi, @arunavabasu-03  would you like to look into it? @erwanp what are the deliverables for https://github.com/radis/radis/issues/278, I will be pushing it to 0.15 in the meantime

**Comment by arunavabasu-03** [comment]
@anandxkumar , i go with the conda-forge !! I try my best to do that as soon as possible 😄 !

**Comment by arunavabasu-03** [comment]
@erwanp closing !! talking with vaex team for the problem !!

**Comment by erwanp** [comment]
👍

**Pull request closed without merging**
