### PR TITLE
Fixed instances of s+ -> rs+

### LINKED ISSUE #678: Compatibility with python 3.13 - invalid escape sequence
### 🐛 Describe the bug

The presence of a `\` in a string will produce an error in python 3.13, and a warning in python 3.12, see https://adamj.eu/tech/2022/11/04/why-does-python-deprecationwarning-invalid-escape-sequence/

Radis is full of these invalid escape sequences. See for instance the log of this build from read the docs:
```
Running Sphinx v8.0.2
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/conf.py:420: SyntaxWarning: invalid escape sequence '\s'
  "preamble": "\setcounter{tocdepth}{3}",
loading translations [en]... done
making output directory... done
Matplotlib is building the font cache; this may take a moment.
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
[autosummary] generating autosummary for: dev/developer.rst, features/description.rst, features/features.rst, features/thermo.rst, hitran-spectra/hitran-spectra.rst, index.rst, lbl/gpu.rst, lbl/lbl.rst, los/los.rst, modules.rst, online/online.rst, references/references.rst, spectrum/spectrum.rst
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/hitranapi.py:1542: SyntaxWarning: invalid escape sequence '\d'
  and len(re.findall("\d", str(err))) >= 2
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/db/molparam.py:252: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(file, comment="#", sep="\s+")
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/hitempapi.py:240: SyntaxWarning: invalid escape sequence '\S'
  inputfiles = re.findall('href="(\S+.zip)"', response_string)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/lbl/broadening.py:401: SyntaxWarning: invalid escape sequence '\&'
  """(This function is derived from exojax.spec.atomll.gamma_vald3)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:61: SyntaxWarning: invalid escape sequence '\('
  x.str.replace("\(", "", regex=True)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:62: SyntaxWarning: invalid escape sequence '\)'
  .str.replace("\)", "", regex=True)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:63: SyntaxWarning: invalid escape sequence '\['
  .str.replace("\[", "", regex=True)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:64: SyntaxWarning: invalid escape sequence '\]'
  .str.replace("\]", "", regex=True)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:123: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(file, sep="\s+", header=2)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:147: SyntaxWarning: invalid escape sequence '\s'
  pfTdat = pd.read_csv(io.StringIO(pfT_str), sep="\s+")
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/api/kuruczapi.py:153: SyntaxWarning: invalid escape sequence '\s'
  pfdat = pd.read_csv(f, sep="\s+", comment="#", names=pfTdat.index)
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/levels/partfunc.py:236: SyntaxWarning: invalid escape sequence '\ '
  "On-the-fly tabulation of partition functions require Vaex. Install it. /!\ as of June 2024 Vaex is not available on Python>=3.11 "
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/levels/partfunc_cdsd.py:89: SyntaxWarning: invalid escape sequence '\s'
  parsum = pd.read_csv(database, comment="#", sep="\s+")
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/levels/partfunc_cdsd.py:322: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(energy_levels, comment="#", sep="\s+")
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/spectrum/rescale.py:1139: SyntaxWarning: invalid escape sequence '\l'
  """
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/spectrum/compare.py:193: SyntaxWarning: invalid escape sequence '\s'
  """Get a regularized Euclidian distance between two spectra ``s1`` and
/home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/radis/lbl/factory.py:116: SyntaxWarning: invalid escape sequence '\&'
  """A class to put together all functions related to loading CDSD / HITRAN
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.api.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.db.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.io.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.lbl.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.levels.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.los.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.misc.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.phys.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.spectrum.rst, /home/docs/checkouts/readthedocs.org/user_builds/radis/checkouts/677/docs/gen_modules/radis.tools.rst
WARNING: Failed to import api.
``` 

### 💡 Possible solutions

As described in https://adamj.eu/tech/2022/11/04/why-does-python-deprecationwarning-invalid-escape-sequence/ simply replace `"\s"` by `r"\s"` or `"\\s"`

### 🎲 Radis version

0.15

### 💻 Operating system

Windows

### PR DESCRIPTION
**Pull request by Akcol**
### Description

This pull request addresses invalid escape sequences in string literals that produce a SyntaxWarning in Python 3.12 and will raise an error in Python 3.13. Specifically, it replaces instances of sep="\s+" with sep=r"\s+" to resolve this issue.

Fixes #678

### CODE REVIEW

**Comment by Akcol** [comment]
Hi!

Apologies, I thought I'd be able to submit more than one pull request. So far, as mentioned in the original PR, I've fixed some instances of "\" by converting them to r"\". Additionally, I've added two test cases, test_npy.py and test_spec_hdf.py, to help improve test coverage.

**Comment by dcmvdbekerom** [comment]
Hello Ackol! Thanks, for the modifications, I ran pre-commit to make sure all the formatting is adhering to the radis standard. I'd like to merge this quickly because I just tried to fix the development branch and apperantly the escape issues are present there as well. 

Let's wait to see if the tests pass, is so then we can merge this.

**Comment by dcmvdbekerom** [comment]
Hi Nicolas, I think the escape characters are required, it's just that in regular strings the single '\' escapes whatever comes after, so that the string that is passed to the docs is a regular &, which I think is giving issues.

This can be remidied by either a dubble escape for each ampersand: '\\&', or by using an literal string by preceeding the string with an r: r"bla bla \& bla". But you may be more knowledgeable on whether they needed to be escaped in the first place.

**Comment by minouHub** [comment]
I'm not very knowledgeable on this matter. I simply checked that

1. The old implementation of the reference `[Barklem-\&-Collet-2016]_` in `plot_1partitionFunction_potentialLowering.py` was actually not redirecting to anything in the last doc successfully built 
2. That Python 3.13 accepted a `&` in a string, see [here](https://radis--709.org.readthedocs.build/en/709/auto_examples/1_Spectra_handling/plot_1partitionFunction_potentialLowering.html#sphx-glr-auto-examples-1-spectra-handling-plot-1partitionfunction-potentiallowering-py)

For sure, Sphinx was not happy about "\&". The best would be to correctly put a reference to the [bibliography](https://radis--709.org.readthedocs.build/en/709/references/references.html#klarenaar2017), which I might do but later. If you have a better option, feel free to implement it 👍

**Comment by dcmvdbekerom** [comment]
Well you fixed the problem so definitely you are more knowledgeable🙂
Ready to merge?

**Comment by minouHub** [comment]
Well ... I solved the database problem with ExoMol. For `\&`, I didn't do much

**Comment by minouHub** [comment]
Well done @Akcol for your first contribution!

**Pull request merged**
