### PR TITLE
Compute power based on vacuum wavelengths - Resolution proposal for bug #460

### LINKED ISSUE #460: Integrals based on wavelength differs from integrals based on wavenum by a factor of 1.00027
Original comment from @AllanHOlesenBW  

---

**Integrals based on wavelength differs from inte

> grals based on wavenum by a factor of 1.00027.**
> At first, I thought that this was just a numerical error in the integrals. But it seems very consistent. And the error is suspiciously close to the refraction index for air.
> 
> An example of this can be seen in bug #454 where @erwanp performs a check of integrals after conversions of emisscoeff, based on wavenum and wavelength:
> 
> > Also checking that the integral is properly conserved in both cases :
> > 
> > 0.001534377339562196
> > 0.0015347955335563383
> 
> These two numbers are actually different by a factor of 1.00027
> 
> A demonstration example:
> 
> ```
> from radis import calc_spectrum
> s = calc_spectrum(1900, 2300, # cm-1
>         molecule='CO',
>         isotope='1,2,3',
>         pressure=1.01325, # bar
>         Tgas=700, # K
>         mole_fraction=0.1,
>         path_length=1, # cm
>         databank='hitran', # or use 'hitemp'
>     )
> 
> print('Wave unit:    ', s.get_waveunit())
> print('Radiance unit:', s.units['radiance'])
> 
> print('Testing different methods of integrating the radiance over the full spectrum.')
> print()
> print('First the specific built-in method, Spectrum.get_power()')
> print('This uses an internal rescaling of waveunit to nm to get a meaningful integral:')
> power1 = s.get_power(unit='W/m2/sr')
> print(power1)
> 
> print()
> print('Replicate this using the generic built-in integration method, also converting to wavelength:')
> power2 = s.get_integral("radiance_noslit", wunit="nm", Iunit="W/m2/sr/nm")
> print(power2)
> print('Ratio between this result and get_power()', power2/power1)
> 
> print()
> print('Do the same, but this time maintain the wavenum based units:')
> power3 = s.get_integral("radiance_noslit", wunit="cm-1", Iunit="W/m2/sr/cm-1")
> print(power3)
> print('Ratio between this result and get_power()', power3/power1)
> 
> print()
> print('Test again with wavelength base, but this time use nm_vac as wunit:')
> power4 = s.get_integral("radiance_noslit", wunit="nm_vac", Iunit="W/m2/sr/nm")
> print(power4)
> print('Ratio between this result and get_power()', power4/power1)
> ```
> 
> I would expect that if I specify wunit="nm", Iunit="W/m2/sr/nm" in an integral, then those nm are the same type of nanometers, either vacuum based or air based. 
> 
> And if I specify wunit="cm-1", Iunit="W/m2/sr/cm-1", I expect those to be the same type of wavenums, either vacuum based or air based.
> 
> Something clearly deviates  from this expectation since I get different results, but I am not sure which of the results are correct.

_Originally posted by @AllanHOlesenBW in https://github.com/radis/radis/issues/215#issuecomment-1112985821_

### PR DESCRIPTION
**Pull request by AllanHOlesenBW**
### Description

This pull request is to address the wavelength problem described in bug #460.

Fixes #460

### CODE REVIEW

**Review by erwanp — APPROVED** [review]

**Comment by erwanp** [comment]
Hello, thanks for contributing. For some reason the test suite wasn't started (maybe because yo'ure a first time contributor). I'll start it manually by overwritting one of your changes

**Comment by AllanHOlesenBW** [comment]
Was the missing test something I should have initiated, or was it supposed to happen automatically when I made the pull request?

**Comment by erwanp** [comment]
It is supposed to happen automatically, nothing needed on your side. Happened to us recently (https://github.com/radis/radis/pull/426#issuecomment-1068317814) .  @gagan-aryan I think you fixed it last time. Can you try to push (linting for isntance?) to Allan's branch ?

**Comment by erwanp** [comment]
Error in tests https://app.travis-ci.com/github/radis/radis/jobs/571013983#L1815
seen to be due to the different value of get_power()

Given that the new one is more physically accurate we should update the test reference value

**Comment by erwanp** [comment]
Btw @AllanHOlesenBW , we'll release a new Radis version soon. To implement your changes, can you update the hardcoded power value to the new (corrected) value ?

**Comment by AllanHOlesenBW** [comment]
> Btw @AllanHOlesenBW , we'll release a new Radis version soon. To implement your changes, can you update the hardcoded power value to the new (corrected) value ?

I see no hardcoded power value in my code. Are you referring to a hardcoded value in the unit test? If yes, I will try to figure that out.

**Comment by erwanp** [comment]
Yes, it is this value in `radis/test/spectrum/test_spectrum.py` : https://app.travis-ci.com/github/radis/radis/jobs/571013983#L1815

(the value is expected to change since the old method was using the wrong wavelengths)

**Comment by erwanp** [comment]
@AllanHOlesenBW I'm delaying this to the next release (0.14), please tell us if you need help updating the hardcoded value to pass the tests

**Comment by erwanp** [comment]
@AllanHOlesenBW if you need us to update the value, please tell us !

**Comment by anandxkumar** [comment]
Hi @AllanHOlesenBW any updates?

**Comment by minouHub** [comment]
@AllanHOlesenBW nothing happened in this PR for almost a year. If you cannot devote time for it anymore it's perfectly fine and but we need to be aware of it :)

**Comment by erwanp** [comment]
Merging, i'll fix if necessary

**Pull request merged**
