### PR TITLE
Added documentation for linting

### LINKED ISSUE #60: Code linting documentation
With #58 @ritzvik added Black as a linting style for RADIS 🥇 

- [ ]  We need to update the Developer Guide, which is currently there:    https://radis.readthedocs.io/en/latest/dev/developer.html

Import things to mention on using Black:

- [x] In Dev Guide: Mention how to include it in your Editor?  https://github.com/psf/black#editor-integration
- [x] add a pre-commit.yaml in RADIS https://github.com/psf/black#version-control-integration
- [x] add pre-commit in the developer requirements
- [x] In Dev Guide: Mention how to setup pre-commit. `pre-commit install`

### PR DESCRIPTION
**Pull request by ritzvik**
@erwanp 
Fixes #60 
I promised this to @minouHub :)

Kindly suggest any changes, or this is good to go from my side.

### CODE REVIEW

**Comment by erwanp** [comment]
Updated some changes to include `pre-commit`, but i don't know how to add new files directly in the PR, or modify other files than the one you've edited. 

I'd also:

- add a `.pre-commit-config.yaml` file in the root folder, with the following content:
```
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
```

Add `pre-commit` in `setup.py`: 

```
    extras_require={
        "dev": [
            "numpydoc",  # for Jedi (autocompletion) to recognize
            "black",  # for code-linting in accordance to PEP8
            "isort",  # for sorting imports
            "pre-commit",    # to enforce Black before each commit (see Dev Guide)
        ]
```

**Comment by ritzvik** [comment]
I’ll do the needful tomorrow
And I’ll be more than happy to walk you through the steps of adding commits to other’s PR.

**Comment by ritzvik** [comment]
I applied the changes

**Comment by ritzvik** [comment]
For pushing to other's PRs, do the following
```
git remote add ritwik https://github.com/ritzvik/radis.git  # set up new remote repo
git checkout -b lint-docs  # make a new branch with the same name as that of the PR
```
synchronize the branch with the PR
```
git reset --hard HEAD~n  # replace n with the number of commits you want to go back from develop. This is because, the PR may may diverged from the develop branch. Otherwise, not required.

git pull --rebase ritwik lint-docs
```

Add the commits you want to add, and then push
```
git push ritwik lint-docs
```

**Comment by erwanp** [comment]
Thanks @ritzvik , i'll keep the link for future PRs!

**Pull request merged**
