### PR TITLE
Quality Checks using Black

### PR DESCRIPTION
**Pull request by ritzvik**
As discussed over Gitter room
@erwanp 

I'll write down the detailed changes in a separate comment

### CODE REVIEW

**Comment by erwanp** [comment]
Great, I'll merge tomorrow! Do the Black test run before the test suite in that .gitlab-ci.yaml "matrix" configuration?

**Comment by erwanp** [comment]
The package crashes on import. Do you think that can be fixed by relative imports of the different modules?

**Comment by ritzvik** [comment]
@erwanp, I know that 
I’ll try to fix that problem today. Please don’t do relative imports. It is not recommended by PEP8

**Comment by ritzvik** [comment]
With this PR, I am not able to implement `isort`, so leaving this PR with only `black` implemented.
Too much changes required for `isort` to work correctly especially in : 
  - `radis/__init__.py`
  - `radis/misc/*.py`
  - `radis/db/*.py`

We'll open a seperate issue about this.

**Comment by ritzvik** [comment]
@erwanp 
Few points to be noted with this PR

  - `pip install ./` would install all the basic packages while `pip install ./[dev]` would install the basic packages and also the packages required for development like `black` and `isort`. Kindly see the changes made in `setup.py`. Also, I believe, `numpydoc` should be moved to `[dev]` packages. But it's up to you.
  - Code can be formatted with `black /file/or/directory/path`. Kindly mention these changes if there is a developer guide in `radis`. I believe a separate section for "Code Linting" should be added. Thoughts?
  - I've updated `.travis.yml` to run two jobs parallely, one to check code style and another runs the usual tests.

Kindly provide your suggestions, and then we can go on with finalizing this PR

**Comment by erwanp** [comment]
Hi ! Amazing work on all that linting. I'll add a code linting section in the developer guide tomorrow. In the meantime I'm merging. 

I'd also like to add a pre-test format check like pep8speaks. Did you add it in EinsteinPy? If so can we configure it with the Black syntax?

**Comment by erwanp** [comment]
Also agreed to move numpydocs to dev, I'll do it on the main branch tomorrow unless you do it in this PR today

**Comment by ritzvik** [comment]
If it’s fine by you, then please go ahead and merge this. It’ll be some time before I can get back to my laptop ( I have a few errands to run ).
Yes we have PEP8speaks in EinsteinPy, but it was added by my friend, who also maintains the package. I personally find this redundant as the quality checks are already being done in CI and I think that PEP8speaks clutters the PR. Anyway, that’s your decision to take, and if you ever make up your mind for it, just copy-paste the configuration file from EinsteinPy repo.

Also, please move numpydoc and other suitable packages to dev in your own time.

**Comment by ritzvik** [comment]
I moved `numpydoc` also

**Pull request merged**
