### PR TITLE
Improve appy_slit calculation time

### PR DESCRIPTION
**Pull request by CorentinGrimaldi**
### Description

Modified the convolution method from numpy.convolve() to scipy.signal.oaconvolve().
This is much faster for the convolution of a long array (the spectrum) with a short one (slit function).
Greatly improves the calculation time.

Also update a test with hardcoded references.

### CODE REVIEW

**Comment by erwanp** [comment]
Nice addition ! 
Can you provide a small example of the performance difference here ?

For instance 
```
# calculate a spectrum 
from radis import calc_spectrum
s = calc_spectrum(1900, 2300,         # cm-1
                  molecule='CO',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  databank='hitran',  # or use 'hitemp'
                  )
# fake it to be very high resolution, with 3M spectral grid points : 
import numpy as np
s.resample(np.linspace(s.get_wavenumber().min(), s.get_wavenumber().max(),int(3e6)), 'cm-1')
```
Compute apply slit time : 
```
%timeit s.apply_slit(0.5, 'nm')
``` 
Before the modification I get 
```
>>> 5.98 s ± 129 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)     
```

**Comment by CorentinGrimaldi** [comment]
Yes !
For the same case, now I get :

`>>> 692 ms ± 40.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

Which is considerably faster !

**Comment by erwanp** [comment]
Definitly, well done ! @dcmvdbekerom did you know of this convolution method ? 
(merging soon)

**Comment by dcmvdbekerom** [comment]
Very interesting! Great find!
I've seen overlap-add mentioned some time ago but never gave it a second thought.. Happy to see it is this much faster!

This could have implications for the FFT method as well, although there we already benefit from the fact that we only need a single FFT instead of three, but still very much worth investigating...

**Review by dcmvdbekerom — APPROVED** [review]

**Comment by dcmvdbekerom** [comment]
One comment on this, also related to the discussion over on the [slack channel](https://app.slack.com/client/T9E5R3R9S/C01TWEPTHFV), is that `np.convolve()` is just an efficient implementation of a direct convolution, i.e., it does not use the FT and therefore scales with N**2 and not NlogN.

So to estimate how much the overlap-add will improve the current FFT implementation, we should really compare it to `scipy.signal.fftconvolve()`. This may be a bit of a semantic discussion however since of course it does not take away the fact that switching overlap-add resulted in some real gains.

**Comment by erwanp** [comment]
(comment on your comment : np.convolve scales as N*M because the two arrays can have a different size,  unlike in FFT.   That's why np.convolve is more efficient for a convolution of a small M kernel over a large N array (ex : a slit function). 

 Overlap-add brings the best of both worlds!)

**Pull request merged**
