### PR TITLE
Added link to Spectra Database

### LINKED ISSUE #431: Make Spectra Database clickable in Radis Flowchart
### 🐛 Describe the issue

This issue addresses one of the documentation goals as mentioned in #77 (14th issue in the first list, to be precise)
- In the current [RADIS Flowchart](https://radis.readthedocs.io/en/latest/_images/RADIS_flow_chart.svg), the Spectra Database at the bottom of the page isn't currently clickable. This issue aims to have a working link for the same.
    - On a side note, some other links such as`Partition Functions`, `Population` and `Line Database` are broken. Some other elements on the page aren't clickable as well.
    - On the right-hand side of the page, the three points, Linestrength cutoff, Weak lines cutoff and Lineshape Broadening cutoff, have the same links. Not sure if this is the expected behaviour or needs to be changed.

### 🎯 Expected behavior

The links should be clickable and should lead to the correct page.
### 💡 Possible solutions

Making changes in the source code for the [RADIS Flowchart](https://github.com/radis/radis/blob/develop/docs/dev/RADIS_flow_chart.svg?short_path=e535c12), adding the appropriate links and submitting a PR after doing the same.

### PR DESCRIPTION
**Pull request by sagarchotalia**
### Description

This pull request is to address adding a clickable link for the Spectra Database element in the flowchart.

Fixes #431

### CODE REVIEW

**Review by gagan-aryan — CHANGES_REQUESTED** [review]
Hey @sagarchotalia ! Thanks for the PR. Can you also fix the links of `Partition Functions`, `Population` and `Line Database` in this PR ?

**Comment by sagarchotalia** [comment]
Yes sure.

**Comment by sagarchotalia** [comment]
Just confirming the links as mentioned above:
`Partition Functions` : https://radis.readthedocs.io/en/latest/lbl/lbl.html#tabulated-partition-functions
`Line Database` : https://radis.readthedocs.io/en/latest/lbl/lbl.html#line-databases
Can you add a link to `Population`? I can't seem to find it in the [LBL Module documentation](https://radis.readthedocs.io/en/latest/lbl/lbl.html#).

**Comment by gagan-aryan** [comment]
> Can you add a link to Population? I can't seem to find it in the [LBL Module documentation](https://radis.readthedocs.io/en/latest/lbl/lbl.html#).

Here it is - https://radis.readthedocs.io/en/latest/source/radis.lbl.base.html

**Comment by sagarchotalia** [comment]
@gagan-aryan is this okay?

**Comment by gagan-aryan** [comment]
Lgtm. Thank you for contributing to RADIS !

**Pull request merged**
