### PR TITLE
Github Workflow Action for Radis

### LINKED ISSUE #103: Install GitHub actions
## Check syntax

Commit 90b9d8f1 created an "undefined name error" in `compare.py`.
The line was not executed in the tests so the error wasn't caught. 

We should add GitHub Action to prevent this from happening again. 

- [ ] [Python Syntax Checker](https://github.com/marketplace/actions/python-syntax-checker) looks good for instance

## Code Linting

- [ ] Following suggestion from @jayanthchandra  we could also add this [Black-code-formatter ](https://github.com/marketplace/actions/black-code-formatter) Action (we already use Black since #58 )

Has anyone experience in implementing GitHub Actions ?

### PR DESCRIPTION
**Pull request by jayanthchandra**
Github Workflow Action for Radis

Description
Have Included Black Formatter and Syntax Check

Fixes #103

### CODE REVIEW

**Comment by jayanthchandra** [comment]
The current syntax check works but some one needs to click on the details to view the errors. I would like to add [this](https://github.com/marketplace/actions/lint-action) as it shows the error in the PR itself. @erwanp : If you let me know the python version to support then i will add this.

**Comment by erwanp** [comment]
I see Lint Action has Black and flake8, that's great !!

**Comment by jayanthchandra** [comment]
Not sure with the current action. I tried one more workflow so that we can see the errors in the PR itself rather than going to action details. I have done the setup for my repo, you can check it [here](https://github.com/jayanthchandra/boilerPlate-flask/pull/4/files). I think that uses the flake configs.

**Comment by erwanp** [comment]
Closing, as current CI on Travis does the job !

**Pull request closed without merging**
