### PR TITLE
removed engine parameter 

### PR DESCRIPTION
**Pull request by 1someshverma**
Removed engine parameter of _calc_spectrum_one_molecule added in previous PR #580 .

### CODE REVIEW

**Comment by 1someshverma** [comment]
@erwanp  I have made the changes but some gpu related test cases are failing ,rest all other tests have passed

**Comment by dcmvdbekerom** [comment]
Hi @1someshverma, that's my bad, I broke some files in the development branch and the easiest way to solve it is to merge https://github.com/radis/radis/pull/604 once it's finished.

For now I've just voided the tests that are failing in your branch, let's wait for the other tests to pass.

Did you still need someone to review this PR?

**Comment by 1someshverma** [comment]
No, I will merge your PR after it is finished.

**Review by erwanp — APPROVED** [review]

**Comment by erwanp** [comment]
@1someshverma you can merge

Btw @dcmvdbekerom you can retrigger the tests [directly from Travis](https://app.travis-ci.com/github/radis/radis/pull_requests)

**Pull request merged**
