### PR TITLE
Templates updated

### PR DESCRIPTION
**Pull request by arunavabasu-03**
This pr contains some updates in the templates for declaring issues and features in the radis . 
I update these templates for the users for radis package can easily describe the issue and I added some checkboxes so that the maintainers of the radis package can easily see whether the issue exists or not (check by the reporter).

Hey @erwanp,  please check this . I think it helps the users for requesting features or declaring an issue.😀
Offical [**Github Reference**](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) that i follow. (YAML Configaration)

### CODE REVIEW

**Comment by anandxkumar** [comment]
Interesting! 
Pros: More detailed and structured issue description is possible.

I tested for the `bug_report.yaml`, it gives two errors:
1) Unique Ids should be present
2) Checkboxes should be unique

You make try to check these yaml by creating issues in your fork. 
- Go to the Settings page of your fork.
- Check the box next to Issues

Check for all 3 templates!

**Comment by arunavabasu-03** [comment]
> Interesting! Pros: More detailed and structured issue description is possible.
> 
> I tested for the `bug_report.yaml`, it gives two errors:
> 
> 1. Unique Ids should be present
> 2. Checkboxes should be unique
> 
> You may try to check these yaml by creating issues in your fork.
> 
> * Go to the Settings page of your fork.
> * Check the box next to Issues
> 
> Check for all 3 templates!

hey @anandxkumar , i fixed all the errors of unique ids.

**Comment by erwanp** [comment]
Hello, thanks for the contribution !

I'm only worried we're adding a lot of details; we should try to keep things simple and minimal. Even current version of templates are a bit too loaded, I think. RADIS is not a massive project and doesn't have tens of issues a day (yet :) ) 

Checkboxes are good in that matter ; but we should also remove all of what's not necessary. We could use your PR to improve this, and clean old messages. For instance : 

- I think the FeatHub & https://github.com/radis/radis/issues/79 features are not working anymore (support discontinued) ; they should be removed.

 - the "Expected behavior" part in issues doesn't bring much value.  (it's already descried in the Bug part)
 
- adding Radis version is a good idea. You can mention `radis.get_version()` 👍

- "Have you spent some time to check if this issue has been raised before?" is really useful for massive projects where maintainers waste a lot of time answering all issues. It's really not our problem yet, we can keep it out !


> “Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”   

(same could be said of our Documentation, which grew quite verbosy over time ! )

**Comment by arunavabasu-03** [comment]
ok i keep it simple as per your instractions

**Comment by erwanp** [comment]
Physics test pass (of course); only linting tests didn't. 

@anandxkumar nicely described how to set-up `pre-commit` so you never have to worry about the linting : https://github.com/radis/radis/pull/437#issuecomment-1086566480

**Review by erwanp — APPROVED** [review]

**Review by erwanp — APPROVED** [review]

**Comment by arunavabasu-03** [comment]
hey @erwanp , any other chenges i have to make ??

**Comment by anandxkumar** [comment]
Hi @arunavabasu-03, can you share the parsed output of YAML by creating an issue in your fork for each of the issues just to validate the output. Also, the lining failed so you may check and try to resolve it by following https://github.com/radis/radis/pull/437#issuecomment-1086566480 steps.

**Comment by arunavabasu-03** [comment]
hey @anandxkumar, please check anything else is wrong ??

**Comment by erwanp** [comment]
We're good, I'll let @anandxkumar merge!

**Review by anandxkumar — APPROVED** [review]

**Comment by anandxkumar** [comment]
Good work @arunavabasu-03, merging!

**Pull request merged**
